
title: 数字大岭山
url: 'http://junlulocky.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: 乡下仔  ## put your name
title: '数字大岭山'  ## your title
location: 广东 , 东莞


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
