
title: 数字大岭山
url: 'http://junlulocky.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: 数字大岭山  ## put your name
title: '立足大岭山，共建大岭山。'  ## your title
location: 广东 , 东莞


## Social Profiles
home: http://www.idalingshan.com/  ## your facebook account url
info: http://www.jefare.com/bless  ## your twitter account url
more: http://www.morejia.com/  ## your linkedin account url
weibo: http://www.github.com/  ## you dribbble account url
email: http://www.linux.org/  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
